name: TASC issue
description: Raise an issue for TASC to review
title: "[Issue]: "
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form to raise an issue at TASC. Your issue will be reviewed at the earliest oppertunity
  - type: textarea
    id: problem
    attributes:
      label: Issue statement
      description: What is the issue you have noted
      value: Please describe the issue here
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution(s)
      description: What solutions have you considered to resolve this issue?
      value: Please describe your solution. If you do not have one yet leave this section blank
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: What additional context or knowledge is needed?
      value: Please provide any additional pieces of information you feel is relevant to this issue
    validations:
      required: false
  - type: checkboxes
    id: raising-group
    attributes:
      label: Which work stream/groups are raising the issue?
      description: You may select more than one. You can select other and mention the group below
      options:
        - label: Clin/Pheno
        - label: Cloud
        - label: Data Security
        - label: DURI
        - label: Discovery
        - label: GKS
        - label: LSG
        - label: REWS
        - label: DaMaSC
        - label: GIF
        - label: Tech team
        - label: Other
    validations:
      required: true
  - type: input
    id: other-raising-group
    attributes:
      label: If you selected other, please state the additional groups (e.g. driver projects)
      placeholder: Please state the groups and comma separate them
  - type: checkboxes
    id: impact-group
    attributes:
      label: Which work stream/groups do you think will be impacted by this?
      description: You may select more than one or leave this blank
      options:
        - label: Clin/Pheno
        - label: Cloud
        - label: Data Security
        - label: DURI
        - label: Discovery
        - label: GKS
        - label: LSG
        - label: REWS
        - label: DaMaSC
        - label: GIF
        - label: Tech team
        - label: Other
    validations:
      required: false
  - type: input
    id: other-impact-group
    attributes:
      label: If you selected other, please state those impacted groups (e.g. driver projects)
      placeholder: Please state the groups and comma separate them
    validations:
      required: false
