"""Generate the ADR and recommendation READMEs from the JSON indexes.

Reads ``index/*-index.json`` (never the markdown documents) so the READMEs can
only ever show what the website sees. Run it after ``python -m tasc_index``::

    python -m tasc_index.readmes
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path, PurePosixPath
from urllib.parse import quote

from tasc_index.models import AdrStatus, RecommendationStatus

REPO_ROOT = Path(__file__).resolve().parents[2]
RECENT_COUNT = 3

NOTICE = (
    "<!-- Generated by tools/tasc_index/readmes.py from {source}. "
    "Do not edit by hand: change the source document and the workflow will regenerate this. -->"
)
RECENT_START = "<!-- tasc-recent:start (generated by tools/tasc_index/readmes.py) -->"
RECENT_END = "<!-- tasc-recent:end -->"
RECENT_ANCHOR = "## Table of Contents"


def load_documents(index_file: Path) -> list[dict[str, str]]:
    return json.loads(index_file.read_text(encoding="utf-8"))["documents"]


def link(doc: dict[str, str], from_dir: str, label: str) -> str:
    """Markdown link to a document, relative to the directory holding the README."""
    rel = PurePosixPath(os.path.relpath(doc["path"], from_dir or "."))
    return f"[{cell(label)}]({quote(rel.as_posix())})"


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def adr_label(doc: dict[str, str]) -> str:
    return f"{doc['id']} {doc.get('short_name') or doc['name']}"


def table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


def latest(documents: list[dict[str, str]]) -> list[dict[str, str]]:
    """The most recent documents, newest first (ties broken by id)."""
    return sorted(documents, key=lambda d: (d["date"], d["id"]), reverse=True)[:RECENT_COUNT]


def render_adr_readme(adrs: list[dict[str, str]]) -> str:
    rows = [
        [
            link(d, "adr", adr_label(d)),
            d["date"],
            cell(d["status"]),
            cell(d["description"]),
        ]
        for d in sorted(adrs, key=lambda d: d["id"])
    ]
    return (
        "# TASC Architectural Decision Records\n\n"
        f"{NOTICE.format(source='index/adr-index.json')}\n\n"
        "Architectural Decision Records (ADRs) capture what TASC decided, why, and the "
        "consequences. ADRs still in `Draft` live in [drafts](../drafts/). "
        "To propose an ADR, start from [template.md](template.md).\n\n"
        + table(["ADR", "Date", "Status", "Description"], rows)
        + "\n"
    )


def render_recommendation_readme(documents: list[dict[str, str]]) -> str:
    rows = [
        [
            link(d, "recommendations", d["name"]),
            d["id"],
            d["type"].capitalize(),
            d["date"],
            cell(d["status"]),
            cell(d["description"]),
        ]
        for d in sorted(documents, key=lambda d: (d["type"] != "recommendation", d["id"]))
    ]
    return (
        "# TASC Recommendations\n\n"
        f"{NOTICE.format(source='index/recommendation-index.json')}\n\n"
        "Recommendations are TASC outputs that guide GA4GH work streams and products. "
        "Governance documents are listed with them. "
        "To propose a new document, start from [template.md](template.md).\n\n"
        + table(["Title", "ID", "Type", "Date", "Status", "Description"], rows)
        + "\n"
    )


def render_recent_section(adrs: list[dict[str, str]], recs: list[dict[str, str]]) -> str:
    """The generated block for the root README, markers included."""

    def bullets(docs: list[dict[str, str]], label_of) -> str:
        if not docs:
            return "_None yet._"
        return "\n".join(f"- {link(d, '', label_of(d))} ({d['date']})" for d in docs)

    recent_adrs = latest(
        [d for d in adrs if d["type"] == "adr" and d["status"] == AdrStatus.ACCEPTED.value]
    )
    recent_recs = latest(
        [
            d
            for d in recs
            if d["type"] == "recommendation" and d["status"] == RecommendationStatus.APPROVED.value
        ]
    )
    return (
        f"{RECENT_START}\n"
        "## Recently Approved\n\n"
        "### Architectural Decision Records\n\n"
        f"{bullets(recent_adrs, adr_label)}\n\n"
        "See [all ADRs](adr/README.md) for the full list and statuses.\n\n"
        f"### Recommendations\n\n{bullets(recent_recs, lambda d: d['name'])}\n\n"
        "See [all recommendations](recommendations/README.md) for the full list and statuses.\n"
        f"{RECENT_END}\n"
    )


def splice_recent(readme: str, section: str) -> str:
    """Replace the generated block in the root README, or insert it before the anchor."""
    if RECENT_START in readme and RECENT_END in readme:
        before, rest = readme.split(RECENT_START, 1)
        _, after = rest.split(RECENT_END, 1)
        return before + section.rstrip("\n") + after
    if RECENT_ANCHOR not in readme:
        raise ValueError(f"root README has neither the generated markers nor '{RECENT_ANCHOR}'")
    before, after = readme.split(RECENT_ANCHOR, 1)
    return f"{before}{section}\n{RECENT_ANCHOR}{after}"


def generate(root: Path, index_dir: Path) -> list[Path]:
    """Write the three generated files; returns the paths written."""
    adrs = load_documents(index_dir / "adr-index.json")
    recs = load_documents(index_dir / "recommendation-index.json")

    root_readme = root / "README.md"
    outputs = {
        root / "adr" / "README.md": render_adr_readme(adrs),
        root / "recommendations" / "README.md": render_recommendation_readme(recs),
        root_readme: splice_recent(
            root_readme.read_text(encoding="utf-8"), render_recent_section(adrs, recs)
        ),
    }
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
    return list(outputs)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="tasc_index.readmes",
        description="Generate adr/README.md, recommendations/README.md and the root README "
        "'Recently Approved' section from the index JSON files.",
    )
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help="repository root")
    parser.add_argument("--index-dir", type=Path, help="default: <root>/index")
    args = parser.parse_args(argv)
    try:
        written = generate(args.root, args.index_dir or args.root / "index")
    except (ValueError, KeyError, OSError) as exc:
        print(f"README generation failed: {exc!r}", file=sys.stderr)
        return 1
    for path in written:
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
